import { Activity, AlertTriangle, BadgeCheck, Layers3 } from "lucide-react";
import { assetUrl } from "../api";
import type { AnalysisResult } from "../types";

const gradeLabels = ["No DR", "Mild", "Moderate", "Severe", "Proliferative DR"];
const lesionLabels: Record<string, string> = { MA: "Microaneurysms", HE: "Hemorrhages", EX: "Hard exudates", SE: "Soft exudates" };

function ProbabilityBars({ values }: { values: Record<string, number> }) {
  return <div className="probability-bars">{Object.entries(values).map(([label, value]) => <div key={label}><span><strong>{label}</strong><small>{(value * 100).toFixed(1)}%</small></span><div><i style={{ width: `${Math.max(value * 100, 1)}%` }} /></div></div>)}</div>;
}

export function StagePlaceholder({ stage, result }: { stage: string; result: AnalysisResult }) {
  if (stage === "about") return <section className="stage-page"><h1>About the project</h1><p>RetinaGram’s local model visualizer exposes the repository’s existing retinal pipeline for technical inspection.</p><div className="result-layout"><div className="result-hero"><Layers3 /><span><small>Pipeline</small><strong>4 real models</strong><p>Quality, restoration, grade classification, and lesion segmentation</p></span></div><div className="clinical-note"><AlertTriangle size={17} />Research and development visualization only. It does not replace review by a qualified clinician.</div></div></section>;
  if (stage === "input") return <section className="stage-page"><h1>Input image</h1><p>The source image validated and stored for this local analysis session.</p><div className="single-image"><img src={assetUrl(result.input_image_url)} alt="Uploaded input image" /></div></section>;
  if (stage === "quality") return <section className="stage-page"><h1>Image quality assessment</h1><p>EfficientNet-B0 features feed the calibrated three-class IQA head.</p>{result.quality ? <div className="result-layout"><div className="result-hero"><Activity /><span><small>Predicted quality</small><strong>{result.quality.quality}</strong><p>{Math.round(result.quality.confidence * 100)}% confidence · {result.quality.metric}</p></span></div><ProbabilityBars values={result.quality.probabilities} /></div> : <Unavailable />}</section>;
  if (stage === "grade") {
    const values = Object.fromEntries((result.grade?.probabilities ?? []).map((value, index) => [`Grade ${index} · ${gradeLabels[index]}`, value]));
    return <section className="stage-page"><h1>DR grade classification</h1><p>ConvNeXt Tiny estimates five DR grade probabilities from the selected retinal image.</p>{result.grade ? <div className="grade-layout"><div className="result-layout"><div className="result-hero"><BadgeCheck /><span><small>Predicted DR grade</small><strong>Grade {result.grade.predicted_grade}</strong><p>{gradeLabels[result.grade.predicted_grade]} · {Math.round(result.grade.confidence * 100)}% confidence</p></span></div><ProbabilityBars values={values} /></div><div className="gradcam-card"><h2>Grad-CAM attention</h2>{result.grade.gradcam_url ? <img src={assetUrl(result.grade.gradcam_url)} alt="Grade model Grad-CAM overlay" /> : <Unavailable />}<p>Attention indicates regions influencing the classifier; it is not a lesion segmentation mask.</p></div></div> : <Unavailable />}</section>;
  }
  if (stage === "lesion") return <section className="stage-page"><h1>Lesion segmentation</h1><p>MobileNetV3-Large UNet++ predicts independent lesion probability channels.</p>{result.lesions ? <><div className="lesion-layout"><div className="single-image"><img src={assetUrl(result.lesions.overlay_url)} alt="Combined predicted lesion mask overlay" /></div><div className="lesion-list">{result.lesions.channel_order.map((name) => { const item=result.lesions!.classes[name]; return <div key={name}><span className={`lesion-code ${name.toLowerCase()}`}>{name}</span><span><strong>{lesionLabels[name]}</strong><small>{item.detected ? `${item.num_regions} predicted region${item.num_regions === 1 ? "" : "s"}` : "No retained region"}</small></span><b>{item.image_percentage.toFixed(3)}%</b></div>; })}</div></div><p className="clinical-note"><AlertTriangle size={17} />{result.lesions.localization_note}</p></> : <Unavailable />}</section>;
  return <section className="stage-page"><h1>Final report</h1><p>A concise record of the model outputs available from this local analysis.</p><div className="report-grid"><div><small>Quality</small><strong>{result.quality?.quality ?? "Unavailable"}</strong></div><div><small>Restoration</small><strong>{result.restoration ? "Completed" : "Unavailable"}</strong></div><div><small>DR grade</small><strong>{result.grade ? `Grade ${result.grade.predicted_grade}` : "Unavailable"}</strong></div><div><small>Lesion classes</small><strong>{result.lesions ? Object.values(result.lesions.classes).filter((item) => item.detected).length : "Unavailable"}</strong></div></div><div className="clinical-note"><Layers3 size={17} />Research visualization only. Review source imagery and model limitations before interpreting outputs.</div></section>;
}

function Unavailable() { return <div className="unavailable"><AlertTriangle size={20} />This stage did not return a result. Review the warning above for recovery details.</div>; }
