#pragma once

#include <QDateTime>
#include <QVariantMap>
#include <array>

namespace retina::reporting {

inline const QString disclaimer = QStringLiteral("This report is generated by an AI-assisted retinal screening system and is not a substitute for professional medical diagnosis.");
inline const QStringList lesionCodes = {"MA", "HE", "EX", "SE"};
inline const QStringList lesionNames = {"Microaneurysms", "Hemorrhages", "Hard Exudates", "Soft Exudates"};

QString gradeLabel(const QVariant &grade);
QString qualityLabel(const QString &quality);
QString qualityMessage(const QString &quality);
QString recommendation(const QVariant &grade);
QString confidenceText(const QVariant &confidence);
QString assetPath(const QString &name);

// Adapt the saved native result at the report boundary; never change inference.
QVariantMap withContext(QVariantMap result, QVariantMap patient, const QString &eye,
                        const QDateTime &scanTime = {}, const QString &originalPath = {});

struct Data {
    explicit Data(const QVariantMap &result);
    QVariantMap patient;
    QString runId, device, scanTime, eye, original, restored, overlay, quality;
    QVariant grade, confidence;
    // -1 means unavailable; 0 and 1 mean not detected and detected.
    std::array<int, 4> lesions{{-1, -1, -1, -1}};
    QString lesionStatus(int index) const;
    QList<QPair<QString, QString>> metadata() const;
};

// Shared by current-patient, History and Batch exports.
bool writePdf(const QString &path, const QVariantMap &result,
              const QDateTime &generatedAt = QDateTime::currentDateTime());

} // namespace retina::reporting
